coroutine.yield({ type = "mount", mountpoint = "/", fspath = "system:/boot/kernel/fs/rootfs" })
coroutine.yield({ type = "mount", mountpoint = "/proc", fspath = "/boot/kernel/fs/procfs" })
coroutine.yield({ type = "mount", mountpoint = "/dev/popen", fspath = "/boot/kernel/fs/pipefs" })

local unistd = require("unistd")
local ifd, ofd = unistd.pipe()
unistd.write(ifd, "1")
unistd.write(ifd, "2")
print(unistd.read(ofd))
unistd.write(ifd, "3")
print(unistd.read(ofd))
unistd.close(ifd)
print(unistd.read(ofd))
