local unistd = require("unistd")
local dirent = require("dirent")
local signal = require("signal")

coroutine.yield()
coroutine.yield()
coroutine.yield()
coroutine.yield()
coroutine.yield()
coroutine.yield({ type = "exit", code = 0 })
